using System;

namespace JulieInventoryMVC_Models.InvoiceMaster
{
    public class InvoiceDetail
    {
        public int InvDetailId { get; set; }
        public int InvId { get; set; }
        public int TItemId { get; set; }
        public double Rate { get; set; }
        public double TItemQty { get; set; }
        public double Amt { get; set; }
        public int ReadyQty { get; set; }
        public int DeliveredQty { get; set; }
        public string Remark { get; set; }
        public string ImgPath { get; set; }
        public byte[] TItemImage { get; set; }
        public int PurchaseDetailId { get; set; }
        public int SrNo { get; set; }
        public string UOM { get; set; }
        public int UId { get; set; }
        public double Pcs { get; set; }
        public double ItemTot { get; set; }
        public double DiscPer { get; set; }
        public double DiscAmt { get; set; }
        public double AQty { get; set; }
        public string AUOM { get; set; }
        public int TS_Id { get; set; }
        public double CST_Per { get; set; }
        public double CST_Amt { get; set; }
        public double CST_AddPer { get; set; }
        public double CST_AddAmt { get; set; }
        public double VAT_Per { get; set; }
        public double VAT_Amt { get; set; }
        public double VAT_AddPer { get; set; }
        public double VAT_AddAmt { get; set; }
        public double Length { get; set; }
        public double Width { get; set; }
        public double SqMtr { get; set; }
        public int RefLedgerId { get; set; }
        public string SrNum { get; set; }
        public string Status { get; set; }
        public string Remark1 { get; set; }
        public double JWExp { get; set; }
        public double MatExp { get; set; }
        public double OtherExp { get; set; }
        public double PurchaseRate { get; set; }
        public double Profit { get; set; }
        public string ItemStatus { get; set; }
        public string M1 { get; set; }
        public string M2 { get; set; }
        public string M3 { get; set; }
        public string M4 { get; set; }
        public string M5 { get; set; }
        public string M6 { get; set; }
        public string M7 { get; set; }
        public string M8 { get; set; }
        public string M9 { get; set; }
        public string M10 { get; set; }
        public string M11 { get; set; }
        public string M12 { get; set; }
        public string M13 { get; set; }
        public string M14 { get; set; }
        public string M15 { get; set; }
        public string M16 { get; set; }
        public string M17 { get; set; }
        public string M18 { get; set; }
        public string M19 { get; set; }
        public string M20 { get; set; }
        public string M21 { get; set; }
        public string M22 { get; set; }
        public string M23 { get; set; }
        public string M24 { get; set; }
        public string M25 { get; set; }
        public string M26 { get; set; }
        public string M27 { get; set; }
        public string M28 { get; set; }
        public string M29 { get; set; }
        public string M30 { get; set; }
        public string M31 { get; set; }
        public string M32 { get; set; }
        public string M33 { get; set; }
        public string M34 { get; set; }
        public string M35 { get; set; }
        public string M36 { get; set; }
        public string M37 { get; set; }
        public string M38 { get; set; }
        public string M39 { get; set; }
        public string M40 { get; set; }
        public string M41 { get; set; }
        public string M42 { get; set; }
        public string M43 { get; set; }
        public string M44 { get; set; }
        public string M45 { get; set; }
        public string M46 { get; set; }
        public string M47 { get; set; }
        public string M48 { get; set; }
        public string M49 { get; set; }
        public string StyleNotes1 { get; set; }
        public string StyleNotes2 { get; set; }
        public string SP1 { get; set; }
        public double SP1Per { get; set; }
        public double SP1Amt { get; set; }
        public double SP1Comm { get; set; }
        public string SP2 { get; set; }
        public double SP2Per { get; set; }
        public double SP2Amt { get; set; }
        public double SP2Comm { get; set; }
        public DateTime DeliveryDate { get; set; }
        public DateTime TrialDate { get; set; }
        public double TaxableAmt { get; set; }
        public double ItemTotal { get; set; }
        public double ItemAmt { get; set; }
        public string Img1 { get; set; }
        public string Img2 { get; set; }
        public string Img3 { get; set; }
        public string Img4 { get; set; }
        public string Img5 { get; set; }
        public bool IsAlteration { get; set; }
        public double OtherCharges { get; set; }
        public int FabricDetailId { get; set; }
        public int TailoringDetailId { get; set; }
        public double FabricCutQty { get; set; }
        public string LIFlag { get; set; }
        public int Measurementby { get; set; }

    }
}
